# -*- coding: utf-8 -*-
"""SQL.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bG-Dfp1eWotu-8CLX7I5lJcdEchkb5cw
"""

import pandas as pd
import sqlite3

bookdata = pd.read_csv('books.csv')  #book data

bookdata = bookdata[['title', 'authors', 'categories', 'published_year']]

conn = sqlite3.connect('your_database.db')

# Store the DataFrame in a single table 'books' in the SQLite database
bookdata.to_sql('books', conn, if_exists='replace', index=False)

# Commit the changes to the database
conn.commit()

# records from the 'books' table
cursor = conn.cursor()
cursor.execute("SELECT DISTINCT authors FROM books ORDER BY published_year");
authors = cursor.fetchall()

cursor.execute("SELECT DISTINCT categories FROM books")
categories = cursor.fetchall();

# Printing the fetched rows
#for author in authors:
    #print(author)


print("Now print all the distinct categories of the books")

#for category in categories:
    #print(category)

cursor.execute("SELECT COUNT(*) AS entry_count FROM books");
print(cursor.fetchall())

cursor.execute("INSERT INTO books (title, authors, categories, published_year) VALUES (?, ?, ?, ?)", ("The Lightning Thief", "Rick Riordan", "Fantasy", 2005))
cursor.execute("SELECT COUNT(*) AS entry_count FROM books");

#check if the book got added
print(cursor.fetchall())

#find books over 2018
cursor.execute("SELECT title, authors FROM books WHERE published_year >= 2018");
selections  = cursor.fetchall()

for selection in selections:
  print("Title " + selection[0] + " author: " + selection[1])

cursor.execute("SELECT DISTINCT published_year FROM books")
years = cursor.fetchall()

years = [year[0] for year in years if year[0] is not None] # dont want any nones

max_year = max(years)
min_year = min(years)

print(f"Maximum year: {max_year}")
print(f"Minimum year: {min_year}")

# Close the connection
conn.close()